### ISSUE TITLE
It seems I have encountered a GPU-related error

### ISSUE THREAD

**Issue by Thatfreesky** [josedolz/LiviaNET#1] opened 2017-06-05 15:01 UTC

**Comment by Thatfreesky** [comment] 2017-06-05 15:25
A small problem, I have solved it

**Comment by Thatfreesky** [comment] 2017-06-05 15:37
```
mountain@Mountain:~$ cd GitHub/
mountain@Mountain:~/GitHub$ git clone https://github.com/josedolz/LiviaNET.git
Cloning into 'LiviaNET'...
remote: Counting objects: 644, done.
remote: Total 644 (delta 0), reused 0 (delta 0), pack-reused 644
Receiving objects: 100% (644/644), 10.28 MiB | 17.00 KiB/s, done.
Resolving deltas: 100% (364/364), done.
Checking connectivity... done.
mountain@Mountain:~/GitHub$ source activate biomediclasagne
(biomediclasagne) mountain@Mountain:~/GitHub$ cd LiviaNET/
(biomediclasagne) mountain@Mountain:~/GitHub/LiviaNET$ cd src/
(biomediclasagne) mountain@Mountain:~/GitHub/LiviaNET/src$ python ./networkTraining.py ./LiviaNET_Config.ini 0
/home/mountain/anaconda3/envs/biomediclasagne/lib/python2.7/site-packages/theano/gpuarray/dnn.py:135: UserWarning: Your cuDNN version is more recent than Theano. If you encounter problems, try updating Theano or downgrading cuDNN to version 5.1.
  warnings.warn("Your cuDNN version is more recent than "
Using cuDNN version 6020 on context None
Mapped name None to device cuda0: GeForce GTX 750 Ti (0000:01:00.0)
 ******************************************  CREATING NETWORK ******************************************
 --- Creating model (Reading parameters...)
 **********************  Starting creation model **********************
 ------------------------ General ------------------------ 
 - Network name: liviaTest
 - Folder to save the outputs: LiviaNet_Test
 ------------------------ CNN Architecture ------------------------  
 - Number of classes: 9
 - Layers: [10, 20, 30, 100]
 - Kernel sizes: [[3, 3, 3], [3, 3, 3], [3, 3, 3], [1]]
 - Intermediate connected CNN layers: []
 - Pooling: [[1, 1, 1], [1, 1, 1], [1, 1, 1]]
 - Dropout: [0.25, 0.5]
 --- Activation function: PReLU
 --- Weights initialization (CNN Layers): Delving
 --- Weights initialization (FCN Layers): Delving
 ------------------------ Training Parameters ------------------------  
 - Learning rate: [0.001]
 - Batch size: 10
 - Apply batch normalization in 20 epochs
 ------------------------ Size of samples ------------------------  
 - Training: [25, 25, 25]
 - Testing: [45, 45, 45]
...[STATUS]: Building the Network model...
 - Shape of input subvolume (Training): (10, 1, 25, 25, 25)
 - Shape of input subvolume (Testing): (10, 1, 45, 45, 45)
 --- [STATUS]  --------- Creating layer 0 --------- 
 --- Activation function: PReLU
 --- Weights initialization type: Delving 
 ----- (Training) Input shape: (10, 1, 25, 25, 25)  ---> Output shape: [10, 10, 23, 23, 23]  ||  kernel shape [10, 1, 3, 3, 3]
 ----- (Testing) Input shape: (10, 1, 45, 45, 45)   ---> Output shape: [10, 10, 43, 43, 43]
 --- [STATUS]  --------- Creating layer 1 --------- 
 --- Activation function: PReLU
 --- Weights initialization type: Delving 
 ----- (Training) Input shape: [10, 10, 23, 23, 23]  ---> Output shape: [10, 20, 21, 21, 21]  ||  kernel shape [20, 10, 3, 3, 3]
 ----- (Testing) Input shape: [10, 10, 43, 43, 43]   ---> Output shape: [10, 20, 41, 41, 41]
 --- [STATUS]  --------- Creating layer 2 --------- 
 --- Activation function: PReLU
 --- Weights initialization type: Delving 
 ----- (Training) Input shape: [10, 20, 21, 21, 21]  ---> Output shape: [10, 30, 19, 19, 19]  ||  kernel shape [30, 20, 3, 3, 3]
 ----- (Testing) Input shape: [10, 20, 41, 41, 41]   ---> Output shape: [10, 30, 39, 39, 39]
 --- Starting to create the fully connected layers....
 --- [STATUS]  --------- Creating layer 3 --------- 
 --- Activation function: PReLU
 --- Weights initialization type: Delving 
 ----- (Training) Input shape: [10, 30, 19, 19, 19]  ---> Output shape: [10, 100, 19, 19, 19]  ||  kernel shape [100, 30, 1, 1, 1]
 ----- (Testing) Input shape: [10, 30, 39, 39, 39]   ---> Output shape: [10, 100, 39, 39, 39]
 ----- (Classification layer) kernel shape [9, 100, 1, 1, 1]
 --- [STATUS]  --------- Creating layer 3 --------- 
 --- Activation function: Linear
 --- Weights initialization type: Delving 
 ----- (Training) Input shape: [10, 100, 19, 19, 19]  ---> Output shape: [10, 9, 19, 19, 19]  ||  kernel shape [9, 100, 1, 1, 1]
 ----- (Testing) Input shape:  [10, 100, 39, 39, 39]  ---> Output shape: [10, 9, 39, 39, 39]
 ------- Initializing network training parameters...........
 --- Optimizer: RMS Prop
 ----------------- Starting compilation process ----------------- 
 --- Cost function: negativeLogLikelihood
 --- Optimizer: RMS Prop
 ...Compiling the training function...
 ...The training function was compiled...
 ...Compiling the testing function...
 ...The testing function was compiled...
..Folder Networks created...
..Folder to store predictions (Validation) created...
..Folder to store predictions (Testing) created...
 Network model saved in /home/mountain/GitHub/LiviaNET/src/outputFiles/LiviaNet_Test/Networks as liviaTest_Epoch0
 ******************************************  NETWORK CREATED ******************************************
 ******************************************  STARTING NETWORK TRAINING ******************************************
 ************************************************  STARTING TRAINING **************************************************
 **********************  Starting training model (Reading parameters) **********************
 --- Training model (Reading parameters...)
 --- Do training in 3 epochs with 2 subEpochs each...
-------- Reading Images names used in training/validation -------------
 ================== Images for training ================
 Image(0): MR_Img1.mat  |  GT: GT_Img1.mat  |  ROI ROI_Img1.mat 
 Image(1): MR_Img2.mat  |  GT: GT_Img2.mat  |  ROI ROI_Img2.mat 
 Image(2): MR_Img3.mat  |  GT: GT_Img3.mat  |  ROI ROI_Img3.mat 
 Image(3): MR_Img4.mat  |  GT: GT_Img4.mat  |  ROI ROI_Img4.mat 
 Image(4): MR_Img5.mat  |  GT: GT_Img5.mat  |  ROI ROI_Img5.mat 
 ================== Images for validation ================
 Image(0): MR_Img6.mat  |  GT: GT_Img6.mat  |  ROI ROI_Img6.mat 
 ===============================================================
 ... Loading model from /home/mountain/GitHub/LiviaNET/src/outputFiles/LiviaNet_Test/Networks/liviaTest_Epoch0
 ... Network architecture successfully loaded....
 ============== EPOCH: 1/3 =================
 --- SubEPOCH: 1/2
 ... Get samples for subEpoch...
 ... getting 200 samples per subject...
...Processing subject: 1. 20.0 % of the whole training set...
...Processing subject: 2. 40.0 % of the whole training set...
...Processing subject: 3. 60.0 % of the whole training set...
...Processing subject: 4. 80.0 % of the whole training set...
...Processing subject: 5. 100.0 % of the whole training set...
 ---------- Cost of this subEpoch: 1.62791441798
 --- SubEPOCH: 2/2
 ... Get samples for subEpoch...
 ... getting 200 samples per subject...
...Processing subject: 1. 20.0 % of the whole training set...
...Processing subject: 2. 40.0 % of the whole training set...
...Processing subject: 3. 60.0 % of the whole training set...
...Processing subject: 4. 80.0 % of the whole training set...
...Processing subject: 5. 100.0 % of the whole training set...
 ---------- Cost of this subEpoch: 1.0529193294
 ---------- Training on Epoch #0 finished ----------
 ---------- Cost of Epoch: 1.34041687369 / Mean training error 1.34041687369
 -------------------------------------------------------- 
--------------------  Starting validation ------------------------
-------------  Segmenting subject: MR_Img6.mat ....total: 1/1... -------------
Traceback (most recent call last):
  File "./networkTraining.py", line 82, in <module>
    networkTraining(sys.argv[1:])
  File "./networkTraining.py", line 77, in networkTraining
    startTraining(networkModelName,configIniName)
  File "/home/mountain/GitHub/LiviaNET/src/LiviaNet/startTraining.py", line 213, in startTraining
    0 # Validation (0) or testing (1)
  File "/home/mountain/GitHub/LiviaNET/src/LiviaNet/startTesting.py", line 120, in segmentVolume
    predictions = myNetworkModel.networkModel_Test(0)
  File "/home/mountain/anaconda3/envs/biomediclasagne/lib/python2.7/site-packages/theano/compile/function_module.py", line 898, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "/home/mountain/anaconda3/envs/biomediclasagne/lib/python2.7/site-packages/theano/gof/link.py", line 325, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/home/mountain/anaconda3/envs/biomediclasagne/lib/python2.7/site-packages/theano/compile/function_module.py", line 884, in __call__
    self.fn() if output_subset is None else\
RuntimeError: Can't make contiguous copy
Apply node that caused the error: HostFromGpu(gpuarray)(InplaceGpuDimShuffle{0,2,3,4,1}.0)
Toposort index: 232
Inputs types: [GpuArrayType<None>(float32, 5D)]
Inputs shapes: [(10, 100, 39, 39, 39)]
Inputs strides: [(23727600, 6084, 156, 4, 608400)]
Inputs values: ['not shown']
Outputs clients: [['output']]

HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.
```

**Comment by josedolz** [comment] 2017-06-05 17:15
Hi, can you give me your config files to try to reproduce the error in my computer? 

Thanks.

**Comment by Thatfreesky** [comment] 2017-06-06 00:11
OK
The LiviaNET_Config.ini
```
############################################################################################################################################
#################################################        CREATION OF THE NETWORK       #####################################################
############################################################################################################################################


############## =================== General Options  =================  ################
[General]
networkName = liviaTest
# Saving Options
folderName = LiviaNet_Test


############## =================== CNN_Architecture  =================  ################
[CNN_Architecture]
numkernelsperlayer = [10,20,30,100]

# Kernels shapes:  (Note, if kernel size is equal to 1 on one layer means that this layer is fully connected)
# In this example there will be 3 conv layers and 1 fully connected layer (+ classification layer)
kernelshapes = [[3, 3, 3], [3, 3, 3], [3, 3, 3], [1]]

# Intermediate layers to connect to the last conv layer (just before the first fully connected layer)
intermediateConnectedLayers = []

# In the current implementation it does not support pooling (To be done...)
pooling_scales = [[1,1,1],[1,1,1],[1,1,1]]

# Array size should be equal to number of fully connected (FC) layers + classification layer
dropout_Rates = [0.25,0.5] 

# Non-linear activations
# Type: 0: Linear
#       1: ReLU
#       2: PReLU
#       3: LeakyReLU
activationType = 2

# TODO. Include activation type for Softmax layer
# Number of classes: background + classes to segment
n_classes = 9

# ------- Weights initialization ----------- #
# There are some ways to initialize the weights. This is defined by the variable "weight_Initialization"
# Here, there is a list of supported methods
# 0, Classic
# 1: Delving (He, Kaiming, et al. "Delving deep into rectifiers: Surpassing human-level performance on imagenet classification." ICCV'15)
# 2: Load Pre-trained
#      ----------
# There is also the choice of which layers will be initialized with pre-trained weights. This is specified in the variable
# "load weight layers". This can be either empty (i.e. all layers will be initialized with pre-trained weights in case 
# "weight_Initialization" is 1)
weight_Initialization_CNN = 1
weight_Initialization_FCN = 1
#load weight layers = [] # Next release
# If using pre-trained models, specify the folder that contains the weights and the indexes of those weights to use
# To ease the transfer between different softwares (i.e matlab for instance), and between different architectures,
# the weights for each layer should be stored as a single file.
# Right now weights have to be in .npy format
weights folderName = /~yourpath/trainedWeights
# Same length as conv layers
weights trained indexes = [0,1,2] 
#weight_Initialization_Sec = 1

############## =================== Training Options  =================  ################
[Training Parameters]
#n_epochs=20
batch_size=10
number Of Epochs = 3
number Of SubEpochs = 2 
number of samples at each SubEpoch Train = 1000
# TODO. To define some changes in the learning rate
learning Rate change Type = 0
# Subvolumes (i.e. samples) sizes.
# Validation equal to testing samples
sampleSize_Train = [25,25,25]
sampleSize_Test  = [45,45,45]

# Cost function values
# 0:
# 1:
costFunction = 0 
SoftMax temperature = 1.0
#### ========= Learning rate ========== #####
L1 Regularization Constant = 1e-6
L2 Regularization Constant = 1e-4

# TO check
# The array size has to be equal to the total number of layers (i.e. CNNs + FCs + Classification layer)
#Leraning Rate = [0.0001, 0.0001, 0.0001, 0.0001,0.0001, 0.0001, 0.0001, 0.0001,0.0001, 0.0001, 0.0001, 0.0001,0.0001, 0.0001 ]
Leraning Rate = [0.001]
# First epoch to change learning rate
First Epoch Change LR = 1
# Each how many epochs change learning rate
Frequency Change LR = 2
# TODO. Add learning rate for each layer

#### ========= Momentum ========== #####
# Type of momentum
# 0: Classic
# 1: Nesterov
Momentum Type = 1
Momentum Value = 0.6
# Use momentum normalized?
momentumNormalized = 1

#### ======== Optimizer ===== ######
# Type: 0-> SGD
#       1-> RMSProp (TODO. Check why RMSProp complains....)
Optimizer Type = 1

#In case we chose RMSProp
Rho RMSProp = 0.9
Epsilon RMSProp = 1e-4

# Apply Batch normalization
# 0: False, 1: True
applyBatchNormalization = 1
BatchNormEpochs = 20

# Apply padding to images
# 0: False, 1: True
applyPadding = 1

############################################################################################################################################
#################################################            TRAINING VALUES           #####################################################
############################################################################################################################################

[Training Images]
imagesFolder = /home/mountain/GitHub/LiviaNET/Dataset/MR/ 
GroundTruthFolder = /home/mountain/GitHub/LiviaNET/Dataset/Label/
# ROI folder will contain the ROI where to extract the pacthes and where to perform the segmentation.
# Values of the ROI should be 0 (non interest) and 1 (region of interest)
ROIFolder = /home/mountain/GitHub/LiviaNET/Dataset/ROI/
# If you have no ROIs
#ROIFolder = []
# Type of images in the dataset
#     0: nifti format
#     1: matlab format
# IMPORTANT: All the volumes should have been saved as 'vol'
imageTypes = 1

# Indexes for training/validation images. Note that indexes should correspond to the position = inex + 1 in the folder,
# since python starts indexing at 0
indexesForTraining = [0,1,2,3,4]
indexesForValidation = [5]

```

The LiviaNET_Segmentation.ini
```

############################################################################################################################################
#################################################         SEGMENTATION PARAMETERS      #####################################################
############################################################################################################################################

[Segmentation Images]
imagesFolder = /home/mountain/GitHub/LiviaNET/Dataset/MR/ 
GroundTruthFolder = /home/mountain/GitHub/LiviaNET/Dataset/Label/
ROIFolder = /home/mountain/GitHub/LiviaNET/Dataset/ROI/

# TODO.
# Type of images in the dataset
#     0: nifit format
#     1: matlab format
imageTypes = 1

# Indexes correspont to position -1 in the folder
indexesToSegment = [6]

# Apply padding to images
# 0: False, 1: True
applyPadding = 1
```
my LiviaNET Dataset path `/home/mountain/GitHub/LiviaNET/Dataset`

Thanks.

**Comment by josedolz** [comment] 2017-06-06 18:03
Hi, I have tried the code (in two machines and one server) and it works in all of them. Here is the example of running the example.

josed@josed-XPS-8900:~/Documents/Code/Temp$ git clone https://github.com/josedolz/LiviaNET.git
Cloning into 'LiviaNET'...
remote: Counting objects: 644, done.
remote: Total 644 (delta 0), reused 0 (delta 0), pack-reused 644
Receiving objects: 100% (644/644), 10.28 MiB | 5.26 MiB/s, done.
Resolving deltas: 100% (364/364), done.
Checking connectivity... done.
josed@josed-XPS-8900:~/Documents/Code/Temp$ cd LiviaNET/
josed@josed-XPS-8900:~/Documents/Code/Temp/LiviaNET$ cd src/
josed@josed-XPS-8900:~/Documents/Code/Temp/LiviaNET/src$ python ./networkTraining.py ./LiviaNET_Config.ini 0
WARNING (theano.sandbox.cuda): The cuda backend is deprecated and will be removed in the next release (v0.10).  Please switch to the gpuarray backend. You can get more information about how to switch at this URL:
 https://github.com/Theano/Theano/wiki/Converting-to-the-new-gpu-back-end%28gpuarray%29

Using gpu device 0: GeForce GTX 960 (CNMeM is disabled, cuDNN 5110)
 ******************************************  CREATING NETWORK ******************************************
 --- Creating model (Reading parameters...)
 **********************  Starting creation model **********************
 ------------------------ General ------------------------ 
 - Network name: liviaTest
 - Folder to save the outputs: LiviaNet_Test
 ------------------------ CNN Architecture ------------------------  
 - Number of classes: 9
 - Layers: [10, 20, 30, 100]
 - Kernel sizes: [[3, 3, 3], [3, 3, 3], [3, 3, 3], [1]]
 - Intermediate connected CNN layers: []
 - Pooling: [[1, 1, 1], [1, 1, 1], [1, 1, 1]]
 - Dropout: [0.25, 0.5]
 --- Activation function: PReLU
 --- Weights initialization (CNN Layers): Delving
 --- Weights initialization (FCN Layers): Delving
 ------------------------ Training Parameters ------------------------  
 - Learning rate: [0.001]
 - Batch size: 10
 - Apply batch normalization in 20 epochs
 ------------------------ Size of samples ------------------------  
 - Training: [25, 25, 25]
 - Testing: [45, 45, 45]
...[STATUS]: Building the Network model...
 - Shape of input subvolume (Training): (10, 1, 25, 25, 25)
 - Shape of input subvolume (Testing): (10, 1, 45, 45, 45)
 --- [STATUS]  --------- Creating layer 0 --------- 
 --- Activation function: PReLU
 --- Weights initialization type: Delving 
 ----- (Training) Input shape: (10, 1, 25, 25, 25)  ---> Output shape: [10, 10, 23, 23, 23]  ||  kernel shape [10, 1, 3, 3, 3]
 ----- (Testing) Input shape: (10, 1, 45, 45, 45)   ---> Output shape: [10, 10, 43, 43, 43]
 --- [STATUS]  --------- Creating layer 1 --------- 
 --- Activation function: PReLU
 --- Weights initialization type: Delving 
 ----- (Training) Input shape: [10, 10, 23, 23, 23]  ---> Output shape: [10, 20, 21, 21, 21]  ||  kernel shape [20, 10, 3, 3, 3]
 ----- (Testing) Input shape: [10, 10, 43, 43, 43]   ---> Output shape: [10, 20, 41, 41, 41]
 --- [STATUS]  --------- Creating layer 2 --------- 
 --- Activation function: PReLU
 --- Weights initialization type: Delving 
 ----- (Training) Input shape: [10, 20, 21, 21, 21]  ---> Output shape: [10, 30, 19, 19, 19]  ||  kernel shape [30, 20, 3, 3, 3]
 ----- (Testing) Input shape: [10, 20, 41, 41, 41]   ---> Output shape: [10, 30, 39, 39, 39]
 --- Starting to create the fully connected layers....
 --- [STATUS]  --------- Creating layer 3 --------- 
 --- Activation function: PReLU
 --- Weights initialization type: Delving 
 ----- (Training) Input shape: [10, 30, 19, 19, 19]  ---> Output shape: [10, 100, 19, 19, 19]  ||  kernel shape [100, 30, 1, 1, 1]
 ----- (Testing) Input shape: [10, 30, 39, 39, 39]   ---> Output shape: [10, 100, 39, 39, 39]
 ----- (Classification layer) kernel shape [9, 100, 1, 1, 1]
 --- [STATUS]  --------- Creating layer 3 --------- 
 --- Activation function: Linear
 --- Weights initialization type: Delving 
 ----- (Training) Input shape: [10, 100, 19, 19, 19]  ---> Output shape: [10, 9, 19, 19, 19]  ||  kernel shape [9, 100, 1, 1, 1]
 ----- (Testing) Input shape:  [10, 100, 39, 39, 39]  ---> Output shape: [10, 9, 39, 39, 39]
 ------- Initializing network training parameters...........
 --- Optimizer: RMS Prop
 ----------------- Starting compilation process ----------------- 
 --- Cost function: negativeLogLikelihood
 --- Optimizer: RMS Prop
 ...Compiling the training function...
 ...The training function was compiled...
 ...Compiling the testing function...
 ...The testing function was compiled...
..Folder Networks created...
..Folder to store predictions (Validation) created...
..Folder to store predictions (Testing) created...
 Network model saved in /home/josed/Documents/Code/Temp/LiviaNET/src/outputFiles/LiviaNet_Test/Networks as liviaTest_Epoch0
 ******************************************  NETWORK CREATED ******************************************
 ******************************************  STARTING NETWORK TRAINING ******************************************
 ************************************************  STARTING TRAINING **************************************************
 **********************  Starting training model (Reading parameters) **********************
 --- Training model (Reading parameters...)
 --- Do training in 3 epochs with 2 subEpochs each...
-------- Reading Images names used in training/validation -------------
 ================== Images for training ================
 Image(0): MR_Img1.mat  |  GT: GT_Img1.mat  |  ROI ROI_Img1.mat 
 Image(1): MR_Img2.mat  |  GT: GT_Img2.mat  |  ROI ROI_Img2.mat 
 Image(2): MR_Img3.mat  |  GT: GT_Img3.mat  |  ROI ROI_Img3.mat 
 Image(3): MR_Img4.mat  |  GT: GT_Img4.mat  |  ROI ROI_Img4.mat 
 Image(4): MR_Img5.mat  |  GT: GT_Img5.mat  |  ROI ROI_Img5.mat 
 ================== Images for validation ================
 Image(0): MR_Img6.mat  |  GT: GT_Img6.mat  |  ROI ROI_Img6.mat 
 ===============================================================
 ... Loading model from /home/josed/Documents/Code/Temp/LiviaNET/src/outputFiles/LiviaNet_Test/Networks/liviaTest_Epoch0
 ... Network architecture successfully loaded....
 ============== EPOCH: 1/3 =================
 --- SubEPOCH: 1/2
 ... Get samples for subEpoch...
 ... getting 200 samples per subject...
...Processing subject: 1. 20.0 % of the whole training set...
...Processing subject: 2. 40.0 % of the whole training set...
...Processing subject: 3. 60.0 % of the whole training set...
...Processing subject: 4. 80.0 % of the whole training set...
...Processing subject: 5. 100.0 % of the whole training set...
 ---------- Cost of this subEpoch: 1.64080776274
 --- SubEPOCH: 2/2
 ... Get samples for subEpoch...
 ... getting 200 samples per subject...
...Processing subject: 1. 20.0 % of the whole training set...
...Processing subject: 2. 40.0 % of the whole training set...
...Processing subject: 3. 60.0 % of the whole training set...
...Processing subject: 4. 80.0 % of the whole training set...
...Processing subject: 5. 100.0 % of the whole training set...
 ---------- Cost of this subEpoch: 1.04458353043
 ---------- Training on Epoch #0 finished ----------
 ---------- Cost of Epoch: 1.34269564658 / Mean training error 1.34269564658
 ------------------------------  Starting validation ------------------------------ 
-------------  Segmenting subject: MR_Img6.mat ....total: 1/1... -------------
 ... Saving segmentation result... ... Image succesfully saved...
 ... Saving prob map for class 1... ... Image succesfully saved...
 ... Saving prob map for class 2... ... Image succesfully saved...
 ... Saving prob map for class 3... ... Image succesfully saved...
 ... Saving prob map for class 4... ... Image succesfully saved...
 ... Saving prob map for class 5... ... Image succesfully saved...
 ... Saving prob map for class 6... ... Image succesfully saved...
 ... Saving prob map for class 7... ... Image succesfully saved...
 ... Saving prob map for class 8... ... Image succesfully saved...
 ... Computing Dice scores: 
 -------------- DSC (Class 1) : 0.336734074209
 -------------- DSC (Class 2) : 0.0320835664988
 -------------- DSC (Class 3) : 0.0671658724756
 -------------- DSC (Class 4) : 0.0233602875112
 -------------- DSC (Class 5) : 0.365568891651
 -------------- DSC (Class 6) : 0.139053254438
 -------------- DSC (Class 7) : 0.259699511253
 -------------- DSC (Class 8) : 0.11220006759
 ------------------------------  Validation DONE ------------------------------  
 Network model saved in /home/josed/Documents/Code/Temp/LiviaNET/src/outputFiles/LiviaNet_Test/Networks as liviaTest_Epoch1
 ============== EPOCH: 2/3 =================
 --- SubEPOCH: 1/2
 ... Get samples for subEpoch...
 ... getting 200 samples per subject...
...Processing subject: 1. 20.0 % of the whole training set...
...Processing subject: 2. 40.0 % of the whole training set...
...Processing subject: 3. 60.0 % of the whole training set...
...Processing subject: 4. 80.0 % of the whole training set...
...Processing subject: 5. 100.0 % of the whole training set...
 ---------- Cost of this subEpoch: 0.89150477767
 --- SubEPOCH: 2/2
 ... Get samples for subEpoch...
 ... getting 200 samples per subject...
...Processing subject: 1. 20.0 % of the whole training set...
...Processing subject: 2. 40.0 % of the whole training set...
...Processing subject: 3. 60.0 % of the whole training set...
...Processing subject: 4. 80.0 % of the whole training set...
...Processing subject: 5. 100.0 % of the whole training set...
 ---------- Cost of this subEpoch: 0.756551772356
 ---------- Training on Epoch #1 finished ----------
 ---------- Cost of Epoch: 0.824028275013 / Mean training error 1.0833619608
 ------------------------------ Starting validation ------------------------------ 
-------------  Segmenting subject: MR_Img6.mat ....total: 1/1... -------------
 ... Saving segmentation result... ... Image succesfully saved...
 ... Saving prob map for class 1... ... Image succesfully saved...
 ... Saving prob map for class 2... ... Image succesfully saved...
 ... Saving prob map for class 3... ... Image succesfully saved...
 ... Saving prob map for class 4... ... Image succesfully saved...
 ... Saving prob map for class 5... ... Image succesfully saved...
 ... Saving prob map for class 6... ... Image succesfully saved...
 ... Saving prob map for class 7... ... Image succesfully saved...
 ... Saving prob map for class 8... ... Image succesfully saved...
 ... Computing Dice scores: 
 -------------- DSC (Class 1) : 0.36638685911
 -------------- DSC (Class 2) : 0.116625310174
 -------------- DSC (Class 3) : 0.19777182831
 -------------- DSC (Class 4) : 0.0803937653815
 -------------- DSC (Class 5) : 0.423536265657
 -------------- DSC (Class 6) : 0.274455390592
 -------------- DSC (Class 7) : 0.38189229779
 -------------- DSC (Class 8) : 0.139830508475
 ------------------------------  Validation DONE ------------------------------  
 Network model saved in /home/josed/Documents/Code/Temp/LiviaNET/src/outputFiles/LiviaNet_Test/Networks as liviaTest_Epoch2
 ============== EPOCH: 3/3 =================
 --- SubEPOCH: 1/2
 ... Get samples for subEpoch...
 ... getting 200 samples per subject...
...Processing subject: 1. 20.0 % of the whole training set...
...Processing subject: 2. 40.0 % of the whole training set...
...Processing subject: 3. 60.0 % of the whole training set...
...Processing subject: 4. 80.0 % of the whole training set...
...Processing subject: 5. 100.0 % of the whole training set...
 ---------- Cost of this subEpoch: 0.702843154967
 --- SubEPOCH: 2/2
 ... Get samples for subEpoch...
 ... getting 200 samples per subject...
...Processing subject: 1. 20.0 % of the whole training set...
...Processing subject: 2. 40.0 % of the whole training set...
...Processing subject: 3. 60.0 % of the whole training set...
...Processing subject: 4. 80.0 % of the whole training set...
...Processing subject: 5. 100.0 % of the whole training set...
 ---------- Cost of this subEpoch: 0.667074851394
 ---------- Training on Epoch #2 finished ----------
 ---------- Cost of Epoch: 0.68495900318 / Mean training error 0.950560974926
 -------------------------------------------------------- 
 ... Learning rate has been changed from 0.0010000000475 to 0.000500000023749
 ------------------------------  Starting validation ------------------------------ 
-------------  Segmenting subject: MR_Img6.mat ....total: 1/1... -------------
 ... Saving segmentation result... ... Image succesfully saved...
 ... Saving prob map for class 1... ... Image succesfully saved...
 ... Saving prob map for class 2... ... Image succesfully saved...
 ... Saving prob map for class 3... ... Image succesfully saved...
 ... Saving prob map for class 4... ... Image succesfully saved...
 ... Saving prob map for class 5... ... Image succesfully saved...
 ... Saving prob map for class 6... ... Image succesfully saved...
 ... Saving prob map for class 7... ... Image succesfully saved...
 ... Saving prob map for class 8... ... Image succesfully saved...
 ... Computing Dice scores: 
 -------------- DSC (Class 1) : 0.45656426188
 -------------- DSC (Class 2) : 0.251185609158
 -------------- DSC (Class 3) : 0.263640490241
 -------------- DSC (Class 4) : 0.150890674118
 -------------- DSC (Class 5) : 0.441928155616
 -------------- DSC (Class 6) : 0.441134933881
 -------------- DSC (Class 7) : 0.425483028721
 -------------- DSC (Class 8) : 0.273964131107
 ------------------------------  Validation DONE ------------------------------ 
 Network model saved in /home/josed/Documents/Code/Temp/LiviaNET/src/outputFiles/LiviaNet_Test/Networks as liviaTest_Epoch3
................ The whole Training is done.....
 ************************************************************************************ 
 ******************************************  DONE  ******************************************
josed@josed-XPS-8900:~/Documents/Code/Temp/LiviaNET/src$ ^C

**Comment by Thatfreesky** [comment] 2017-06-07 00:43
Thanks for your help. I will try again. 

I want to ask you another question. When I read your source code in sampling.py. I think you divide the samples into two parts by the function:
```python
def getSamplingWeights(gtLabelsImage,
                       roiMask
                       ) :

    foreMask = (gtLabelsImage>0).astype(int)
    backMask = (roiMask>0) * (foreMask==0)
    weightMaps = [ foreMask, backMask ] 
 
    return weightMaps
```
But, what I understand is the only difference between the samples in foreground and the samples in background is the label of its center voxel. For other voxels in a sample, their labels may be any one of the nine labels.  So, I want to ask whether I misunderstand your code.

In addition, I want to try your code on the Brats 2015 training data. But this training data does not contain the ROI mask. In fact, I do not know how to prepare the ROI mask and what is the function of the ROI mask.

**Comment by josedolz** [comment] 2017-06-07 01:39
Hi, 
yes, you understood correctly. Actually, the weights for sampling are thought for the case you want to give more importance to certain regions. Right now are set to the same values in some part of the code. For sampling each individual sample, I take into account its center voxels, as you said, letting the rest of the patch being any other label.

W.r.t. the ROI mask, I did not create a function for it, since it can be very data-dependent. However, it is very easy to create, particularly for the BRATS dataset. I think the skull is stripped in this dataset, so you only need to create a volume where voxels different 0 in a BRATS subject are equal to 1 in your mask. The rest of your mask voxels will be 0.

It would be something like (for example in Matlab notation):

mask = zeros(size(BRATS_Subject));  % Create your mask
id = find(BRATS_Subject !=0);   % Find voxels different to 0
mask(id) = 1;  % Assign 1 to those voxels

I hope it helps.

PS (July,26th,2017): I have added a [function](https://github.com/josedolz/LiviaNET/blob/master/src/generateROI.py) to generate the ROI from an input image.

**Comment by Thatfreesky** [comment] 2017-06-07 03:08
Hi,
Thanks for your guide. You know I am concerning about the unbalance problem in the samples. under your setting, the number of samples with its center voxels labeled as `0` equals the number of samples with nonzero label center voxels. So, this can not guarantee the balance between the whole zero label voxels and nonzero label voxels. Of course, I think this will not be a big problem if the training input size close to the size of receptive field. 
In fact, I want to know that sine this is a multi-class classification problem, whether we should keep the number of zero label voxels closing to the number of nonzero label voxels or we should keep the number of all nine different kind of label voxels closing.

**Comment by josedolz** [comment] 2017-06-08 15:35
Yes, it is true that the sampling strategy in this work is almost naive, but it demonstrated to be enough to get very satisfactory results on this particular application and for this architecture (see results on the ref paper). Maybe improving this strategy, so that the whole number of voxels for the different 9 classes is more balanced, might improve the results...:)

**Closed as completed** 2017-06-15 13:38 UTC
